#!/usr/bin/env bash
#MISE description="List available Hetzner system images (filter with grep, e.g. mise hz:images | grep flatcar)"
set -euo pipefail

fnox exec -- xh --ignore-stdin --check-status --print=b GET "$HCLOUD_API/images" \
  Authorization:"Bearer $HCLOUD_TOKEN" \
  type==system \
| jq -r '.images[] | "\(.name)\t\(.description)\t\(.status)"'
