[Hosts.flutterina]
Components = ["pangolin", "beszel-hub"]
Roles = ["base", "tunneled"]

[Roles.base]
Components = ["restic-backup", "beszel-agent"]

[Roles.tunneled]
Components = ["newt"]

[Hosts.bow]
Components = ["music", "grimmory", "audiobookshelf", "jellyfin", "buildbarn"]
Roles = ["base", "tunneled"]
