Secrets = ["resticPassword", "storageBoxSshKey"]

[Settings]
NoRestart = true

[Defaults]
resticKeepDaily = "7"
resticKeepWeekly = "4"
resticKeepMonthly = "6"
resticOnCalendar = "daily"

[[Services]]
Service = "restic-backup.service"
Stopped = true
Oneshot = true

[[Services]]
Service = "restic-backup-trigger.service"
Stopped = true

[[Services]]
Service = "restic-backup.timer"
Static = true
